permalink: /:year/:month/:day/:title.html
paginate: 20
# markdown: redcarpet

# 作者信息
author: 
  name: 荆中志
  email: zhongzhijing@126.com
  link: http://jingzztech.cn/
  weibo: http://weibo.com/jingzhongzhi
  github: http://github.com/george5814
  csdn: http://blog.csdn.net/kisssun0608
  linkedin: http://www.linkedin.com/in/jingzz
  qq: 1182696993

# 站点信息
title: 荆中志的博客
description: 我的博客
url: http://jingzztech.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/dog.png
favicon: /public/img/dog.png

# disqus 设置
disqus:
  shortname: jingzz

#多说 设置 
duoshuo:
  shortname: jingzz

# 主题设置，自动激活某个标签
active: tags

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

markdown: kramdown
gems:
    [jekyll-paginate]

port:
    4001