permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Anya Lin
  email: lay.1010@hotmail.com
  link: http://jingzztech.cn
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/lay1010
  music: http://site.douban.com/linanya
  linkedin: http://jingzztech.cn

# 站点信息
title: 荆忠志的博客
description: 我的个人博客
url: http://jingzztech.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/useravatar.png
favicon: /public/img/useravatar.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: jingzztech.cn

# disqus 设置
disqus:
  shortname: jingzztech

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  technology: 技术